import React from "react";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"





const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export const metadata = {
//   title: "Travelbeta Blog: Home",
//   openGraph: {
//       title: "Travelbeta Blog: Home",
//       description: "Travel with us to breathtaking destinations, hidden gems, and exciting adventures. Get inspired and discover the world's best-kept secrets.",
//   },
// };

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <html lang="en">
//             <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//                 {children}
//                 <Analytics />
//             </body>
//         </html>
//     );
// };

const RootLayout = ({ children }) => {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {children}
                <Analytics />
            </body>
        </html>
    );
};
export default RootLayout;